// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InstanceService persists the list of configured Claude Desktop instances
 * and launches isolated Claude Desktop processes against per-instance
 * profile directories.
 * 
 * Every operation below takes the instance's absolute profile path as given
 * by the caller — it never re-derives the path from the current settings.
 * The path is decided once, when an instance is created or registered, and
 * stays pinned even if the user later changes the global instances folder.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DefaultInstance returns the packaged (MSIX/AppX) default Claude Desktop
 * install's profile directory, resolved statically so it can be offered as
 * a routing target even when the process isn't currently running.
 */
export function DefaultInstance(): $CancellablePromise<$models.DefaultInstance> {
    return $Call.ByID(1061404664).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteProfileDir permanently deletes the given absolute directory and
 * everything inside it. Callers are expected to ensure the instance isn't
 * running first — deleting files still open in another process is
 * unreliable on Windows.
 */
export function DeleteProfileDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(3580601913, path);
}

/**
 * EnsureProfileDir creates an instance's profile directory if it does not
 * already exist.
 */
export function EnsureProfileDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(430979012, path);
}

/**
 * Launch starts an isolated Claude Desktop process using the given absolute
 * path as its --user-data-dir.
 */
export function Launch(path: string): $CancellablePromise<void> {
    return $Call.ByID(4019797201, path);
}

/**
 * List returns every configured instance.
 */
export function List(): $CancellablePromise<$models.Instance[]> {
    return $Call.ByID(2200856722).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * MoveDefaultProfileDir relocates the packaged default Claude Desktop
 * install's data. Its processes can't be reliably isolated by profile
 * directory (see claudeProcessesByProfileDir), so instead of stopping just
 * this one, every claude.exe process on the system is stopped — meaning
 * any other running Claude Router instance gets closed too. Callers should
 * warn the user about that before calling this. It also waits considerably
 * longer than MoveProfileDir for everything to fully quiesce.
 */
export function MoveDefaultProfileDir(profileDir: string, oldPath: string, newPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(3176425120, profileDir, oldPath, newPath);
}

/**
 * MoveProfileDir relocates a Claude Router-managed instance's profile
 * directory from oldPath to newPath. The instance must not be running —
 * moving files still open in another process is unreliable on Windows.
 * 
 * When both paths are on the same drive, this is an instant, atomic
 * rename — literally the same MoveFileEx the OS itself uses for a
 * same-volume move ("system tools" as requested). Only when the drives
 * differ (rename fails with a cross-device error) does it fall back to a
 * manual copy-then-delete, reporting progress via the instance:move-progress
 * event as it goes.
 * 
 * Returns whether any file had to be skipped (see ResolveMoveConflict) —
 * when that happens, oldPath is deliberately left in place instead of being
 * deleted, so the skipped data isn't lost.
 */
export function MoveProfileDir(profileDir: string, oldPath: string, newPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(994420691, profileDir, oldPath, newPath);
}

/**
 * OpenProfileDir reveals the given absolute directory in the system file
 * explorer, creating it first if it does not exist yet.
 */
export function OpenProfileDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(3324323594, path);
}

/**
 * ResolveMoveConflict answers a pending instance:move-conflict event —
 * "skip" leaves that one file/folder behind and continues the move, "abort"
 * stops the whole move. No-ops with an error if nothing is pending (e.g. the
 * conflict was already resolved or timed out).
 */
export function ResolveMoveConflict(action: string): $CancellablePromise<void> {
    return $Call.ByID(429103241, action);
}

/**
 * RouteURL launches Claude Desktop with targetURL as a command-line
 * argument, so it hands the redirect off to Claude's own OAuth handling.
 * An empty dataDir targets the packaged default install (no
 * --user-data-dir); otherwise it targets the isolated instance at dataDir,
 * the same way Launch does.
 */
export function RouteURL(dataDir: string, targetURL: string): $CancellablePromise<void> {
    return $Call.ByID(2053307768, dataDir, targetURL);
}

/**
 * RunningProfileDirs returns every currently running Claude Desktop process,
 * matched to its profile directory. There is no PID to remember across app
 * restarts (and a remembered PID can be silently reused by an unrelated
 * process anyway), so instead every claude.exe process on the system is
 * inspected and matched by its --user-data-dir command-line argument.
 */
export function RunningProfileDirs(): $CancellablePromise<$models.RunningInstance[]> {
    return $Call.ByID(3387576370).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Save persists the full list of instances, replacing any previous content.
 */
export function Save(instances: $models.Instance[]): $CancellablePromise<void> {
    return $Call.ByID(1446877123, instances);
}

/**
 * Stop terminates every running Claude Desktop process launched for the
 * given profile directory (an isolated instance can spawn more than one
 * process — main + renderer — all sharing the same --user-data-dir).
 */
export function Stop(profileDir: string): $CancellablePromise<void> {
    return $Call.ByID(3706219630, profileDir);
}

// Private type creation functions
const $$createType0 = $models.DefaultInstance.createFrom;
const $$createType1 = $models.Instance.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.RunningInstance.createFrom;
const $$createType4 = $Create.Array($$createType3);
