// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DefaultInstance describes the packaged (MSIX/AppX) default Claude Desktop
 * install, resolved statically from the installed package — unlike
 * RunningInstance, it doesn't require the process to be currently running,
 * so it can be offered as a routing target even when Claude isn't open.
 */
export class DefaultInstance {
    "profileDir": string;
    "path": string;

    /** Creates a new DefaultInstance instance. */
    constructor($$source: Partial<DefaultInstance> = {}) {
        if (!("profileDir" in $$source)) {
            this["profileDir"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DefaultInstance instance from a string or object.
     */
    static createFrom($$source: any = {}): DefaultInstance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DefaultInstance($$parsedSource as Partial<DefaultInstance>);
    }
}

/**
 * Instance describes a single isolated Claude Desktop instance definition.
 * Path is the absolute profile directory pinned at creation/registration
 * time — it is never recomputed from the current settings, so renaming the
 * global instances root later doesn't strand existing instances.
 */
export class Instance {
    "id": string;
    "name": string;
    "profileDir": string;
    "path": string;
    "createdAt": string;

    /** Creates a new Instance instance. */
    constructor($$source: Partial<Instance> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("profileDir" in $$source)) {
            this["profileDir"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Instance instance from a string or object.
     */
    static createFrom($$source: any = {}): Instance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Instance($$parsedSource as Partial<Instance>);
    }
}

/**
 * MoveConflict describes a file that failed to copy during a move.
 */
export class MoveConflict {
    "profileDir": string;
    "file": string;
    "reason": string;

    /** Creates a new MoveConflict instance. */
    constructor($$source: Partial<MoveConflict> = {}) {
        if (!("profileDir" in $$source)) {
            this["profileDir"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveConflict instance from a string or object.
     */
    static createFrom($$source: any = {}): MoveConflict {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MoveConflict($$parsedSource as Partial<MoveConflict>);
    }
}

/**
 * MoveProgress reports how much of a cross-drive move has completed.
 */
export class MoveProgress {
    "profileDir": string;

    /**
     * CurrentFile is the path (relative to the profile folder) of the file
     * currently being copied, or "" when the move hasn't started copying
     * yet (e.g. still stopping processes) or used the instant same-drive
     * rename fast path.
     */
    "currentFile": string;
    "bytesDone": number;
    "bytesTotal": number;

    /** Creates a new MoveProgress instance. */
    constructor($$source: Partial<MoveProgress> = {}) {
        if (!("profileDir" in $$source)) {
            this["profileDir"] = "";
        }
        if (!("currentFile" in $$source)) {
            this["currentFile"] = "";
        }
        if (!("bytesDone" in $$source)) {
            this["bytesDone"] = 0;
        }
        if (!("bytesTotal" in $$source)) {
            this["bytesTotal"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): MoveProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MoveProgress($$parsedSource as Partial<MoveProgress>);
    }
}

/**
 * RunningInstance is a live claude.exe process matched to its profile
 * directory, discovered by inspecting --user-data-dir on its command line.
 */
export class RunningInstance {
    "profileDir": string;
    "path": string;

    /**
     * IsDefault marks the packaged (MSIX/AppX) default Claude Desktop
     * install — the one launched normally from the Start Menu, not by
     * Claude Router. It behaves specially: process matching for it is
     * unreliable (see claudeProcessesByProfileDir), so moving its data
     * requires stopping every claude.exe process, not just this one.
     */
    "isDefault": boolean;

    /** Creates a new RunningInstance instance. */
    constructor($$source: Partial<RunningInstance> = {}) {
        if (!("profileDir" in $$source)) {
            this["profileDir"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunningInstance instance from a string or object.
     */
    static createFrom($$source: any = {}): RunningInstance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunningInstance($$parsedSource as Partial<RunningInstance>);
    }
}
