/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddInstanceDialog: typeof import('./src/components/instances/AddInstanceDialog.vue')['default']
    AutoSelectTimer: typeof import('./src/components/router/AutoSelectTimer.vue')['default']
    BaseDialog: typeof import('./src/components/ui/BaseDialog.vue')['default']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    DiscoveredInstanceCard: typeof import('./src/components/instances/DiscoveredInstanceCard.vue')['default']
    EditInstanceDialog: typeof import('./src/components/instances/EditInstanceDialog.vue')['default']
    EmptyState: typeof import('./src/components/instances/EmptyState.vue')['default']
    InstanceCard: typeof import('./src/components/instances/InstanceCard.vue')['default']
    PendingUrlPreview: typeof import('./src/components/router/PendingUrlPreview.vue')['default']
    RegisterInstanceDialog: typeof import('./src/components/instances/RegisterInstanceDialog.vue')['default']
    RemoveInstanceDialog: typeof import('./src/components/instances/RemoveInstanceDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterTargetCard: typeof import('./src/components/router/RouterTargetCard.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/settings/SettingsDialog.vue')['default']
    StatusIndicator: typeof import('./src/components/common/StatusIndicator.vue')['default']
    Toggle: typeof import('./src/components/ui/Toggle.vue')['default']
  }
}
