// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Settings holds user-configurable application preferences.
 */
export class Settings {
    /**
     * InstancesRootDir is the folder under which new instance profile
     * directories are created. Empty means "use the default".
     */
    "instancesRootDir": string;

    /**
     * AutoSelectTimeoutSeconds is how long the protocol router picker waits
     * for the user to choose a target before routing to the default install
     * automatically. Clamped to [5, 30]; 0 means "not yet set".
     */
    "autoSelectTimeoutSeconds": number;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("instancesRootDir" in $$source)) {
            this["instancesRootDir"] = "";
        }
        if (!("autoSelectTimeoutSeconds" in $$source)) {
            this["autoSelectTimeoutSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * SettingsView is what the frontend receives: the effective (already
 * defaulted) settings plus derived, read-only information.
 */
export class SettingsView {
    "instancesRootDir": string;

    /**
     * IsOnSystemDrive reports whether InstancesRootDir lives on the same
     * drive as Windows itself — a non-system drive (removable, network,
     * cloud-synced) can be unavailable at launch time or behave oddly with
     * Chromium's profile locking.
     */
    "isOnSystemDrive": boolean;
    "autoSelectTimeoutSeconds": number;

    /** Creates a new SettingsView instance. */
    constructor($$source: Partial<SettingsView> = {}) {
        if (!("instancesRootDir" in $$source)) {
            this["instancesRootDir"] = "";
        }
        if (!("isOnSystemDrive" in $$source)) {
            this["isOnSystemDrive"] = false;
        }
        if (!("autoSelectTimeoutSeconds" in $$source)) {
            this["autoSelectTimeoutSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsView instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsView($$parsedSource as Partial<SettingsView>);
    }
}
