// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService persists user-configurable application preferences, such
 * as the folder under which instance profile directories are created.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get returns the effective settings plus derived, read-only information.
 */
export function Get(): $CancellablePromise<$models.SettingsView> {
    return $Call.ByID(1429206954).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PickInstancesRootDir opens a native folder picker and returns the chosen
 * path, or an empty string if the user cancelled.
 */
export function PickInstancesRootDir(): $CancellablePromise<string> {
    return $Call.ByID(864221196);
}

/**
 * Save persists the given settings.
 */
export function Save(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(1574188955, settings);
}

// Private type creation functions
const $$createType0 = $models.SettingsView.createFrom;
