//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "../../../../../claude_router/core/services/instance/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "instance:move-conflict": $$createType0,
        "instance:move-progress": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = instance$0.MoveConflict.createFrom;
const $$createType1 = instance$0.MoveProgress.createFrom;

configure();
