// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as instance$0 from "../../../../../claude_router/core/services/instance/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "instance:move-conflict": instance$0.MoveConflict;
            "instance:move-progress": instance$0.MoveProgress;
            "router:url-received": string;
        }
    }
}
