// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProtocolService exposes the one user-facing protocol action: opening
 * Windows' Default Apps settings so the user can pick Claude Router.
 * Registration itself is automatic (EnsureRegistered) and not
 * user-toggled — Claude Desktop is a packaged (MSIX) app that declares its
 * own claude:// protocol extension, so being a registered candidate isn't
 * enough by itself; Windows requires the explicit choice made through
 * that settings page.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenDefaultAppsSettings opens Windows' own Default Apps settings page.
 */
export function OpenDefaultAppsSettings(): $CancellablePromise<void> {
    return $Call.ByID(923690164);
}
