// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RouterService exposes the claude:// URL that triggered this launch, if
 * any. Unlike the other services, it holds a small amount of process-
 * lifetime state: the pending URL is decided once at startup (from the
 * command line) or by a forwarded second-instance launch, and stays until
 * the frontend claims it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ClearPendingURL forgets the pending URL once the frontend has taken it,
 * so navigating back to the dashboard doesn't re-show the picker.
 */
export function ClearPendingURL(): $CancellablePromise<void> {
    return $Call.ByID(2898189767);
}

/**
 * GetPendingURL returns the currently pending claude:// URL, or "" if none.
 */
export function GetPendingURL(): $CancellablePromise<string> {
    return $Call.ByID(4203515742);
}

/**
 * SetPendingURL records the claude:// URL to route, overwriting any
 * previous one.
 */
export function SetPendingURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(865342514, url);
}
